name: React App Deployment # name of the workflo

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-react-to-gh-pages:
    runs-on: ubuntu-latest

    steps:
      # checkout the repository content to github runner
      - name: Checkout
        uses: actions/checkout@v4.1.1

      # setup nodejs environment
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.1

      # cache the dependencies to speed up the build
      - name: Cache dependencies
        uses: actions/cache@v3.3.2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}

      # install dependencies
      - name: Install dependencies
        run: npm i

      # build the react app
      - name: Build
        run: npm run build

      # deploy the react app to github pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          # NOTE: GITHUB_TOKEN is a secret token that is automatically generated by GitHub
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build # directory to deploy
